#O que é NumPy

O NumPy oferece funções matemáticas, geradores de números aleatórios, rotinas de álgebra linear, transformadas de Fourier e muito mais.

Com o NumPy é possível trabalhar com numeros em todas as suas formas, como exemplificado na figura abaixo.

| ![Dados](https://i0.wp.com/dadosaocubo.com/wp-content/uploads/2020/07/image1-3.png?w=880&ssl=1) |
|:--:| 
| **Figura** – _Escalares, vetores, matrizes e tensores_ (Fonte da imagem: internet, autor desconhecido) |

In [ ]:
###Importando a biblioteca NumPy
import numpy as np

In [ ]:
###Criando uma estrutura unidimensional
arraynp = np.array(['João', 'Maria', 'José'])
print(arraynp)

['João' 'Maria' 'José']


In [ ]:
#Criar array com numeros aleatórios
#Sintaxe:   numpy.random.randint (menor numero, maior numero - opcional, tamanho - opcional, dtype - opcional)
arrayrandom = np.random.randint(0,100,50)
arrayrandom


array([43, 36, 56, 26, 76, 22, 43, 63,  0, 92, 69, 51, 27, 74, 85, 94, 86,
       94, 85, 68, 89, 59, 34, 95, 55, 11, 83, 13, 30, 77, 24, 99, 36, 59,
       76, 37, 17, 81, 56,  1, 47, 46, 44,  9, 43, 98, 42,  6, 47, 73])

In [ ]:
arraynp2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arraynp2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arrayvazio = [0]*3
type(arrayvazio)
#arrayvazio

list

In [ ]:
arrayvazio2 = np.array(arrayvazio)
type(arrayvazio2)

numpy.ndarray

#Array podem ter listas de tipos diferentes

In [ ]:
arraynp3 = np.array([['altura','largura'],[175,180],[150,140],[180,150]])
arraynp3

array([['altura', 'largura'],
       ['175', '180'],
       ['150', '140'],
       ['180', '150']], dtype='<U21')

#Como ver o tamanho do array?




In [ ]:
print(arraynp.shape)
print(arraynp2.shape)
print(arraynp3.shape)
#linha coluna

(3,)
(3, 3)
(4, 2)


In [ ]:
arraynp4 = np.array([[1],[1]])
arraynp4.shape

(2, 1)

#Como ver as dimensões do array?

![NumPy_ndarray](https://s3-sa-east-1.amazonaws.com/lcpi/b50bd331-732b-48a4-9d46-01f20c15ab29.png "ndarrays")


In [ ]:
print(arraynp.ndim)
print(arraynp2.ndim)
print(arraynp3.ndim)

1
2
2


#Número de elementos

In [ ]:
print(arraynp)
print(arraynp.size)
print(arraynp2)
print(arraynp2.size)
print(arraynp3)
print(arraynp3.size)

['João' 'Maria' 'José']
3
[[10 20 30]
 [40 50 60]
 [70 80 90]]
9
[['altura' 'largura']
 ['175' '180']
 ['150' '140']
 ['180' '150']]
8


#Método arange

In [ ]:
arrayarange = np.arange(20)
arrayarange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arrayarange2 = np.arange(0,50,1)
arrayarange2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Método linspace

In [ ]:
#A diferença aqui é que o último número é a quantidade de elementos no array, e não o incremento
arraylinspace1 = np.linspace(1,10,3)
arraylinspace1

array([ 1. ,  5.5, 10. ])

In [ ]:
arraylinspace2 = np.linspace(0,10,20)
arraylinspace2

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Exercício 1
### Crie um array de com o primeiro elemento sendo o número 5 e o último elemento o número 100, de 5 em 5 números

In [ ]:
arrayfinal = np.arange(5,101,5)
arrayfinal

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

# Exercício 2
### Crie um array de números entre 1 e 20 com 50 números entre eles.

In [ ]:
arrayfinal = np.linspace(1,20,50)
np.round(arrayfinal,2)

NameError: ignored

# Tipagem de dados

In [ ]:
array1 = np.array([-1,2,3,4,-5,6], dtype = str)
array1

array(['-1', '2', '3', '4', '-5', '6'], dtype='<U2')

In [ ]:
array1.dtype

dtype('<U2')

In [ ]:
array2 = np.array([-1,2,3,4,-5,6], dtype = float)
array2

NameError: ignored

In [ ]:
array2.dtype

dtype('float64')

In [ ]:
array3 = np.array([-1,2,3,4,-5,6])
array3.dtype

dtype('int64')

In [ ]:
array4 = np.array([-1,2,3,4,-5,6.0])
array4.dtype

dtype('float64')

In [ ]:
array5 = np.array([-1,2,'3',4,-5,6.0])
array5.dtype

dtype('<U32')

# Cast de array

In [ ]:
array5 = np.array([-1,2,3,4,-5,6.6])
array5

array([-1. ,  2. ,  3. ,  4. , -5. ,  6.6])

In [ ]:
array5.astype(int)

array([-1,  2,  3,  4, -5,  6])

In [ ]:
array5.astype(str)

array(['-1.0', '2.0', '3.0', '4.0', '-5.0', '6.6'], dtype='<U32')

# Exercício 3
### Crie um array de 5 posições que receba 5 números inteiros do usuário e converta esse array para string

In [ ]:
#versão com lista
lista = []

for i in range(5):
  a = int(input('Digite um número inteiro: '))
  lista.append(a)

array = np.array(lista)
arraystring = array.astype(str)
print(lista)
print(array)
print(arraystring)


Digite um número inteiro: 1
Digite um número inteiro: 2
Digite um número inteiro: 3
Digite um número inteiro: 4
Digite um número inteiro: 5
[1, 2, 3, 4, 5]
[1 2 3 4 5]
['1' '2' '3' '4' '5']


In [ ]:
#versão com vetor
vetor = [0]*5
for i in range(5):
  a = int(input('Digite um número inteiro: '))
  vetor[i] = a

array = np.array(vetor)
arraystring = array.astype(str)
print(arraystring)

Digite um número inteiro: 3
Digite um número inteiro: 3
Digite um número inteiro: 3
Digite um número inteiro: 3
Digite um número inteiro: 3


NameError: ignored

#Criando arrays com operações aritméticas em tempo de execução

In [ ]:
array6 = np.arange(0,10)
array6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array7 = np.arange(0,11) * 7
array7

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [ ]:
array8 = np.arange(0,10) ** 2
array8

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#Operações aritméticas com arrays

In [ ]:
arraya = np.arange(0,10)
arrayb = np.arange(0,10)*2
print(arraya)
print(arrayb)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#soma
arraya + arrayb

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#subtração
arrayb - arraya

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#divisão
arraya / arrayb

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [ ]:
#multiplicação
arraya * arrayb

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [ ]:
#comparação de igualdade
arraya == arrayb

array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:
#comparação de maior
arraya > arrayb

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
#comparação de menor
arraya < arrayb

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#Arrays com tamanhos diferentes

In [ ]:
arrayc = np.arange(1,5)
arrayd = np.arange(4,8)
print(arrayc)
print(arrayd)

In [ ]:
#soma
arrayc + arrayd

array([ 5,  7,  9, 11])

# Exercício 4
### Crie dois arrays de 5 elementos aleatórios. Crie um terceiro array com a soma dos elementos anteriores.

In [ ]:
a = np.random.randint(1,5,6)
b = np.random.randint(10,20,5)

if a.shape == b.shape:
  c = a + b
  print(c)
else:
  print('Arrays de tamanho diferente')

6
5
Arrays de shapes diferentes


#Dot Product

In [ ]:
arraya = np.arange(1,4)
arrayb = np.arange(4,7)
print(arraya)
print(arrayb)

In [ ]:
arraya * arrayb

In [ ]:
np.dot(arraya,arrayb)

32

In [ ]:
sum(arraya * arrayb)

#Cópia de Arrays

In [ ]:
arraya = np.arange(0,10)
arraya

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrayb = arraya[5:]
arrayb

array([5, 6, 7, 8, 9])

In [ ]:
arraya[:] = 0
arraya

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arrayb

array([0, 0, 0, 0, 0])

In [ ]:
arraya = np.arange(0,10)
arraya

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrayb = arraya[5:].copy()
arrayb

array([5, 6, 7, 8, 9])

In [ ]:
arraya[:] = 0
arraya

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arrayb

array([5, 6, 7, 8, 9])

#Índices em array

In [ ]:
lista = [1,2,3,4,5,6,7,8,9,10]

vetor = np.array(lista)

print(type(vetor))

<class 'numpy.ndarray'>


In [ ]:
#Tamanho 

print(vetor.shape)

(10,)


In [ ]:
#Primeiro elemento
vetor[0]

1

In [ ]:
#Terceiro elemento 
vetor[2]

3

In [ ]:
#Primeiros 3 elementos
vetor[0:3]

array([1, 2, 3])

In [ ]:
#Todos os valores após o quinto elemento
vetor[5:]

array([ 6,  7,  8,  9, 10])

In [ ]:
#Último elemento
vetor[-1]

10

In [ ]:
#Os últimos três valores
vetor[-3:]

array([ 8,  9, 10])

In [ ]:
#Pegar somente as posicoes pares
vetor[0:10:2]

array([1, 3, 5, 7, 9])

In [ ]:
#Pegar somente as posicoes ímpares
vetor[1:10:2]

array([ 2,  4,  6,  8, 10])

In [ ]:
#Concatenando 2 arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Extras

In [ ]:
arrayarange = np.arange(5)
arrayarange

array([0, 1, 2, 3, 4])

In [ ]:
#soma elementos
arrayarange = np.arange(5)
arrayarange.sum()

10

In [ ]:
#menor elementos
arrayarange = np.arange(5)
arrayarange.min()

0

In [ ]:
#maior elemento
arrayarange = np.arange(5)
arrayarange.max()

4

#Exercícios de fixação


1 - Faça um algoritmo que solicite ao usuário números e os armazene em um vetor de 5 posições. Crie uma função que recebe o vetor preenchido e substitua todas as ocorrência de valores positivos por 1 e todos os valores negativos por 0.


2 - Faça um algoritmo que solicita 2 arrays diferentes de 3 posições que irão representar as 3 notas de 2 alunos da instituição. Após isso, faça a média do somatório de todos os valores dos dois arrays.


Os exercícios devem ser colocado em um repositória Git público e a URL do projeto deve ser enviada para: pablo.bizzi@gmail.com e compartilhar o repositório no Github. Meu usuário é pablobizzi

1 - Faça um algoritmo que solicite ao usuário números e os armazene em um vetor de 5 posições. Crie uma função que recebe o vetor preenchido e substitua todas as ocorrência de valores positivos por 1 e todos os valores negativos por 0.

In [ ]:
def vetor():
  import numpy as np 
  vetor = [0]*5
  for n in range(5):
    f = int(input('Digite um número: '))
    vetor[n] = f
  array = np.array(vetor)
  print(array)
  for n in range(5):
    if array[n] < 0:
      array[n] = 0
    else:
      array[n] =1
  print(array)
vetor()

2 - Faça um algoritmo que solicita 2 arrays diferentes de 3 posições que irão representar as 3 notas de 2 alunos da instituição. Após isso, faça a média do somatório de todos os valores dos dois arrays.

In [ ]:
import numpy as np 
aluno1 = [0]*3
aluno2 = [0]*3
for n in range(3):
  n1 = int(input(f'1° Aluno: Informe a {n+1}° nota: '))
  aluno1[n] = n1
aluno1 = np.array(aluno1)
for n in range(3):
  n2 = int(input(f'2° Aluno: Informe a {n+1}° nota: '))
  aluno2[n] = n2
aluno2 = np.array(aluno2)

print(aluno1)
print(aluno2)
print(f'A media geral é {round(sum(aluno1+aluno2)/(aluno2.size+aluno2.size)),2}')

1° Aluno: Informe a 1° nota: 7
1° Aluno: Informe a 2° nota: 8
1° Aluno: Informe a 3° nota: 7
2° Aluno: Informe a 1° nota: 9
2° Aluno: Informe a 2° nota: 7
2° Aluno: Informe a 3° nota: 5
[7 8 7]
[9 7 5]
A media geral é (7, 2)
